server:
  port: 8888
spring:
  datasource:
    username: root
    password: 123123
    url: jdbc:mysql://localhost/library?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

